apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: backend-services
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/SenavirathneDilan/devops-showcase.git'
    - 'oci://027222547638.dkr.ecr.ap-southeast-1.amazonaws.com'
  destinations:
    - namespace: backend
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'