{{- if .Values.autoscaling.enabled}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ printf "%s-so" .Values.service_name}}
  namespace: {{ .Values.namespace | quote}}
spec:
  scaleTargetRef:
    name: {{ .Values.service_name}}

  minReplicaCount: {{ .Values.autoscaling.minReplicaCount}}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicaCount}}
  cooldownPeriod: {{ .Values.autoscaling.cooldownPeriod | default 300 }}
  pollingInterval: {{ .Values.autoscaling.pollingInterval | default 30 }}

  {{- if .Values.autoscaling.triggers }}
  triggers:
  {{- toYaml .Values.autoscaling.triggers | nindent 4 }}
  {{- end }}
{{- end}}