{{- if .Values.service.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name}}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  selector:
    {{- include "selector.labels" . | nindent 4 }}
{{- end }}
