{{- if .Values.service_account.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-sa" .Values.service_name}}
  namespace: {{ .Values.namespace}}
  annotations:
    {{- toYaml .Values.service_account.annotations | nindent 4}}
{{- end}}