name: Build CRUD API and Publish Documentation
on:
  push:
    branches:
      - development
      - main
    paths:
      - "python-sample-app/version.txt"
env:
  APP_PATH: python-sample-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v4