name: Build CRUD API and Publish Documentation
on:
  push:
    branches:
      - development
      - main
    paths:
      - "python-sample-app/version.txt"
env:
  APP_PATH: python-sample-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v4

      - name: Get Data
        id: get_data
        run: |
          PYTHON_VERSION=$(sed -rn 's/FROM python:([0-9]+\.[0-9]+).*/\1/p' ${{ env.APP_PATH }}/Dockerfile)
          APP_VERSION=$(sed -rn 's/app_version:[[:space:]]*(.*)/\1/p' ${{ env.APP_PATH }}/version.txt)
          echo "python_version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
        working-directory: ${{ env.APP_PATH }}

      - name: Setup Python
        if: steps.get_data.outcome == 'success'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.get_data.outputs.python_version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ env.APP_PATH }}
        if: steps.get_data.outcome == 'success'

      - name: Flake8 Lint
        id: lint
        run: |
          pip install flake8
          flake8 .
        working-directory: ${{ env.APP_PATH }}
        continue-on-error: true

      - name: Docker Build
        if: steps.lint.outcome == 'success'
        run: |
          docker build -t ${{ steps.get_data.outputs.app_version }}-${{ github.sha }} -f ${{ env.APP_PATH }}/Dockerfile ${{ env.APP_PATH }}