name: Build CRUD API and Publish Documentation 
on:
  push:
    branches:
      - development
          # - main
        # paths:
        #   - "python-sample-app/version.txt"
env:
  PATH: python-sample-app
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: CheckOut Code
          uses: actions/checkout@v3

        - name: Get Data
          id: get_data
          run: |
            PYTHON_VERSION=$(sed -rn 's/FROM python:([0-9]+\.[0-9]+.*/\1/p)' Dockerfile)
            APP_VERSION=$(sed -rn 's/app_version:[[:space:]]/p' version.txt)
            echo "python_version=$PYTHON_VERSION" >> GITHUB_OUTPUT
            echo "app_version=$APP_VERSION"
        - name: Setup Python
          if: steps.get_data.outcome == 'success'
          uses: actions/setup-python@v5
          with:
            python-version: ${{steps.get_data.outputs.python_version}}
        - name: flake9 Lint
          id: lint
          uses: py-actions/flake8@v2
        - name: Docker Build
          if: steps.lint.outcome == 'success'
          env:
            FULL_TAG: ${{steps.get_data.outputs.app_version}}-${{github.sha}}
            PATH: ${{env.PATH}}
          run: |
            docker build -t $FULL_TAG $PATH/Dokerfile
          

